name: run_tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .

    - name: Run tests
      run: |
        python -m unittest test_game.py
        pytest
