name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install ALSA development files
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev

    - name: Install dependencies
      run: |
        pip install pygame

    - name: Run tests
      run: |
        python -m unittest test_game.py
