name: run_tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-numpy libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libporttime-dev
        pip install -r requirements.txt
        pip install git+https://github.com/roshan4182/racing_game

    - name: Set SDL_AUDIODRIVER environment variable
      run: echo "export SDL_AUDIODRIVER=dummy" >> $GITHUB_ENV
    - name: Run tests
      run: |
        python -m unittest test_game.py
        pytest
