name: run_tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update && sudo apt-get install -y libasound2-dev  # Install ALSA development files
        pip install -r requirements.txt
        pip install .
    - name: Set SDL_AUDIODRIVER environment variable
      run: echo "export SDL_AUDIODRIVER=dummy" >> $GITHUB_ENV  # Set SDL_AUDIODRIVER to "dummy"
    - name: Run tests
      run: |
        python -m unittest test_game.py
        pytest
